# This file is part of the dune-xt-common project:
#   https://github.com/dune-community/dune-xt-common
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2012 - 2014, 2016)
#   Rene Milk       (2009, 2011 - 2015)
#   Tobias Leibner  (2015)

Module: dune-xt-common
Version: 2.5.0-dev
Maintainer: dune-xt-dev@listserv.uni-muenster.de
Depends: dune-common (>= 2.5) dune-testtools (>= 2.5)
Suggests: dune-fem (>= 2.5) dune-istl (>= 2.5) dune-pybindxi (>= 2.0.1)
